# Generated by Django 5.2.7 on 2025-11-02 13:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_course_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('openai', 'OpenAI GPT'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude')], default='openai', max_length=20)),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=50)),
                ('api_key', models.CharField(help_text='API key for the AI service', max_length=200)),
                ('max_tokens', models.IntegerField(default=1000)),
                ('temperature', models.FloatField(default=0.7)),
                ('daily_request_limit', models.IntegerField(default=1000)),
                ('monthly_token_limit', models.IntegerField(default=100000)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'AI Configuration',
                'verbose_name_plural': 'AI Configurations',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Chat', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_type', models.CharField(choices=[('user', 'User Message'), ('ai', 'AI Response'), ('system', 'System Message')], max_length=10)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('context_used', models.TextField(blank=True, help_text='Course content used for AI response')),
                ('ai_model', models.CharField(blank=True, help_text='AI model used (e.g., gpt-3.5-turbo)', max_length=50)),
                ('tokens_used', models.IntegerField(blank=True, help_text='Tokens consumed for this response', null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tutor.chatsession')),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CourseKnowledgeBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_summary', models.TextField(blank=True)),
                ('topics_summary', models.TextField(blank=True)),
                ('key_concepts', models.TextField(blank=True, help_text='JSON list of key concepts')),
                ('content_embeddings', models.TextField(blank=True, help_text='JSON of content embeddings')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('processing_status', models.CharField(default='pending', max_length=20)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_base', to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='TutorFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_type', models.CharField(choices=[('helpful', 'Helpful'), ('not_helpful', 'Not Helpful'), ('incorrect', 'Incorrect Information'), ('unclear', 'Unclear Response')], max_length=20)),
                ('rating', models.IntegerField(help_text='1-5 rating')),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutor.chatmessage')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TutorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('question', 'General Question'), ('summarize', 'Summarize Content'), ('explain', 'Explain Concept'), ('quiz_help', 'Quiz Help'), ('topic_help', 'Topic Help')], max_length=20)),
                ('user_input', models.TextField()),
                ('ai_response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_time', models.FloatField(blank=True, help_text='Response time in seconds', null=True)),
                ('satisfaction_rating', models.IntegerField(blank=True, help_text='1-5 rating', null=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.chapter')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='tutor.chatsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.topic')),
            ],
        ),
        migrations.CreateModel(
            name='UsageStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('requests_count', models.IntegerField(default=0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('estimated_cost', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usage Statistics',
                'verbose_name_plural': 'Usage Statistics',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
