# Generated by Django 5.2.7 on 2025-11-01 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quiz_quiz_type_chapter_quiz_chapter_topic_quiz_topic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
    ]
