# Generated by Django 5.2.7 on 2025-11-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_remove_quiz_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('design', 'Design'), ('business', 'Business'), ('data_science', 'Data Science'), ('marketing', 'Marketing'), ('photography', 'Photography'), ('music', 'Music'), ('language', 'Language'), ('health', 'Health & Fitness'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
